In [5]:
import pickle
import matplotlib.pyplot as plt
import skimage
%matplotlib inline

import numpy as np

In [13]:
with open("collected_colors.p", "rb") as f:
    colors = pickle.load(f)

In [14]:
colors_arr = np.array(list(colors))

In [15]:
np.random.shuffle(colors_arr)

In [99]:
colors_arr = skimage.color.rgb2hsv(colors_arr/255.)

In [100]:
X = colors_arr[:, 3, :]

In [101]:
y0 = colors_arr[:, 0, :]
y1 = colors_arr[:, 1, :]
y2 = colors_arr[:, 2, :]
y4 = colors_arr[:, 4, :]
y5 = colors_arr[:, 5, :]
y6 = colors_arr[:, 6, :]

# Predicting the second darkest
y = y1

In [102]:
y = y1

In [103]:
train_ratio = 0.7
cutoff = int(train_ratio*len(X))

In [104]:
X_train, X_test = X[:cutoff], X[cutoff:]
y_train, y_test = y[:cutoff], y[cutoff:]

In [105]:
X_train.shape

(319, 3)

In [106]:
y_train.shape

(319, 3)

In [143]:
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.svm import SVR

In [126]:
gbr = GradientBoostingRegressor()

In [127]:
gbr.fit(X_train, y_train[:,0])

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
             learning_rate=0.1, loss='ls', max_depth=3, max_features=None,
             max_leaf_nodes=None, min_impurity_decrease=0.0,
             min_impurity_split=None, min_samples_leaf=1,
             min_samples_split=2, min_weight_fraction_leaf=0.0,
             n_estimators=100, n_iter_no_change=None, presort='auto',
             random_state=None, subsample=1.0, tol=0.0001,
             validation_fraction=0.1, verbose=0, warm_start=False)

In [128]:
gbr.score(X_train, y_train[:,0])

0.9999696407615559

In [129]:
gbr.score(X_test, y_test[:,0])

0.9998528969046232

In [132]:
gbr.predict(X_test[0:3])

array([0.4608945 , 0.20605503, 0.15516808])

In [133]:
y_test[0:3]

array([[0.46273292, 0.95833333, 0.65882353],
       [0.20652174, 0.56097561, 0.32156863],
       [0.15555556, 0.46153846, 0.25490196]])

In [115]:
rfr = RandomForestRegressor(max_depth=5, n_estimators=1000)

In [116]:
rfr.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=5,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=None,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [117]:
print(rfr.score(X_train, y_train))
print(rfr.score(X_test, y_test))

0.9349363623717202
0.9002438200931043


In [134]:
linreg = LinearRegression()

In [135]:
linreg.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [136]:
print(linreg.score(X_train, y_train))
print(linreg.score(X_test, y_test))

0.685629642385456
0.6866351309722831


In [138]:
svr = SVR()

In [140]:
svr.fit(X_train, y_train[:, 0])

/home/max/miniconda3/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
  gamma='auto_deprecated', kernel='rbf', max_iter=-1, shrinking=True,
  tol=0.001, verbose=False)

In [141]:
svr.score(X_train, y_train[:, 0])

0.4383602199972826

In [142]:
svr.score(X_test, y_test[:, 0])

0.41990869525633867

In [145]:
poly = PolynomialFeatures()

In [146]:
poly.fit(X_train)

PolynomialFeatures(degree=2, include_bias=True, interaction_only=False)

In [168]:
from sklearn.linear_model import Lasso, Ridge

In [147]:
linreg = LinearRegression()

In [148]:
linreg.fit(poly.transform(X_train), y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [149]:
linreg.score(poly.transform(X_train), y_train)

0.798854069286786

In [153]:
linreg.score(poly.transform(X_test), y_test)

0.818329490732669

In [154]:
linreg.coef_

array([[ 0.00000000e+00, -8.13568921e-01, -3.01805537e-01,
        -1.41297673e-01,  1.11301760e+00,  3.20186030e-01,
         6.03226726e-04,  1.44523819e-01, -1.70872731e-01,
         1.93460491e-01],
       [ 0.00000000e+00,  9.61530440e-01,  5.98962544e-01,
        -2.38740531e-01, -9.27659090e-01,  2.43486676e-01,
         1.18665986e-02, -1.67704067e-01,  6.80138409e-02,
         2.44264198e-01],
       [ 0.00000000e+00,  4.47982807e-01,  1.39031703e-01,
         6.90430025e-01, -5.29448783e-01,  1.04480461e-01,
         1.22444539e-01, -1.89653215e-01, -2.25515318e-01,
         1.78255070e-01]])

In [151]:
poly.transform(X_train).shape

(319, 10)

In [155]:
poly.powers_

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [2, 0, 0],
       [1, 1, 0],
       [1, 0, 1],
       [0, 2, 0],
       [0, 1, 1],
       [0, 0, 2]])

In [167]:
lasso = Lasso(alpha=0.01)
lasso.fit(poly.transform(X_train), y_train)
print(lasso.score(poly.transform(X_train), y_train))
print(lasso.score(poly.transform(X_test), y_test))

0.6856977887448412
0.7003329089056224


In [169]:
ridge = Ridge()
ridge.fit(poly.transform(X_train), y_train)
print(ridge.score(poly.transform(X_train), y_train))
print(ridge.score(poly.transform(X_test), y_test))

0.7766172463327687
0.7876494988402288
